CREATE TABLE STATES (
    ID INT AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    REGION VARCHAR(20) NOT NULL,
    POPULATION NUMBER(10,0) NOT NULL,
    CAPITAL VARCHAR(50) NOT NULL,
    AREA DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (ID)
);